export const USER_LOGIN_FETCH_START = 'user/LOGIN_FETCH_START';
export const USER_LOGIN_FETCH_END = 'user/LOGIN_FETCH_END';
export const USER_LOGIN_SUCCESS = 'user/LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'user/LOGIN_ERROR';

export const USER_RESET_LOGIN_STATUS = 'user/RESET_LOGIN_STATUS';
